using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CoMS.Entities_Framework;

namespace CoMS.Models
{
    public class RegistrationModel
    {
        private DB db = null;
        public RegistrationModel()
        {
            db = new DB();
        }

        public object ListConferencePackage(int conferenceId)
        {
            var result = db.CONFERENCE_REGISTRATION_PACKAGE.Where(x => x.CONFERENCE_ID == conferenceId)
                .Select(x => new
                {
                    x.CONFERENCE_REGISTRATION_PACKAGE_ID,
                    x.CONFERENCE_ID,
                    x.CONFERENCE_REGISTRATION_PACKAGE_NAME,
                    x.CONFERENCE_REGISTRATION_PACKAGE_NAME_EN,
                    x.EFFECTIVE_FROM_DATE,
                    x.EFFECTIVE_THRU_DATE,
                    x.DESCRIPTION,
                    x.DESCRIPTION_EN,
                    x.CONFERENCE_REGISTRATION_PACKAGE_PRICE,
                    x.CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10,
                    x.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10,
                });

            return result;
        }

    }
}