//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP = new HashSet<ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP>();
            this.ACCOUNT_FOR_CONFERENCE = new HashSet<ACCOUNT_FOR_CONFERENCE>();
        }
    
        public string UserName { get; set; }
        public byte[] Password { get; set; }
        public string Password_Temp { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public Nullable<decimal> CURRENT_GENDER { get; set; }
        public string CURRENT_PHONE { get; set; }
        public string CURRENT_EMAIL { get; set; }
        public string CURRENT_ADDRESS { get; set; }
        public string CURRENT_WARD { get; set; }
        public string CURRENT_DISTRICT { get; set; }
        public string CURRENT_CITY { get; set; }
        public string CURRENT_STATE { get; set; }
        public string CURRENT_ZIPCODE { get; set; }
        public string CURRENT_COUNTRY { get; set; }
        public Nullable<bool> CURRENT_ADDRESS_VISIBLE { get; set; }
        public Nullable<decimal> CURRENT_HOME_ORGANIZATION_ID { get; set; }
        public string CURRENT_HOME_ORGANIZATION_NAME { get; set; }
        public string CURRENT_HOME_ORGANIZATION_NAME_EN { get; set; }
        public string OFFICIAL_IMAGE { get; set; }
        public string EMERGENCY_CONTACT_FULLNAME { get; set; }
        public string EMERGENCY_CONTACT_RELATIONSHIP { get; set; }
        public string EMERGENCY_CONTACT_RELATIONSHIP_EN { get; set; }
        public string EMERGENCY_CONTACT_PHONE_NUMBER { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public Nullable<System.DateTime> FROM_SUSPENDED_DATE { get; set; }
        public Nullable<System.DateTime> TO_SUSPENDED_DATE { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsChangePass { get; set; }
        public Nullable<bool> IsGenPass { get; set; }
        public Nullable<bool> IsGenUserName { get; set; }
        public Nullable<System.DateTime> Reg_GenUserNameDate { get; set; }
        public string CREATED_UserName { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_UserName { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP> ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT_FOR_CONFERENCE> ACCOUNT_FOR_CONFERENCE { get; set; }
    }
}
