//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP
    {
        public string UserName { get; set; }
        public decimal CONFERENCE_REGISTRATION_PACKAGE_ID { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_HANDLING { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public Nullable<decimal> PAYMENT_AMOUNT { get; set; }
        public string PAYMENT_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<bool> PAID_IN_FULL { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATETIME { get; set; }
        public string PAYMENT_IP_ADDRESS { get; set; }
        public string BANK_TRANSFER_NOTE { get; set; }
        public string BANK_TRANSFER_NOTE_EN { get; set; }
        public string BANK_TRANSFER_PAYMENT_REFERENCE_NUMBER { get; set; }
        public string CREDIT_CARD_NUMBER { get; set; }
        public string CREDIT_CARD_FULL_NAME { get; set; }
        public Nullable<short> CREDIT_CARD_EXPIRATION_MONTH { get; set; }
        public Nullable<int> CREDIT_CARD_EXPIRATION_YEAR { get; set; }
        public Nullable<int> CREDIT_CARD_SECURITY_CODE { get; set; }
        public string CREDIT_CARD_ADDRESS { get; set; }
        public string CREDIT_CARD_WARD { get; set; }
        public string CREDIT_CARD_DISTRICT { get; set; }
        public string CREDIT_CARD_CITY { get; set; }
        public string CREDIT_CARD_STATE { get; set; }
        public string CREDIT_CARD_ZIPCODE { get; set; }
        public string CREDIT_CARD_COUNTRY { get; set; }
        public string CREDIT_CARD_PHONE { get; set; }
        public string CREDIT_CARD_NOTE { get; set; }
        public string CREDIT_CARD_NOTE_EN { get; set; }
        public string CREDIT_CARD_TRANSACTION_ID { get; set; }
        public string PAYPAL_PAYMENT_NOTE { get; set; }
        public string PAYPAL_PAYMENT_TRANSACTION_ID { get; set; }
        public string CHECK_PAYMENT_STATUS_NAME { get; set; }
        public string CHECK_PAYMENT_STATUS_NAME_EN { get; set; }
        public string CHECK_PAYMENT_NOTE { get; set; }
        public string CHECK_PAYMENT_NOTE_EN { get; set; }
        public string CHECK_PAYMENT_NUMBER { get; set; }
        public string ONSITE_CASH_PAYMENT_STATUS_NAME { get; set; }
        public string ONSITE_CASH_PAYMENT_NOTE { get; set; }
        public string ONSITE_CASH_PAYMENT_NOTE_EN { get; set; }
        public string ONSITE_CASH_PAYMENT_PAYEE_LAST_NAME { get; set; }
        public string ONSITE_CASH_PAYMENT_PAYEE_FIRST_NAME { get; set; }
        public string ONSITE_CASH_PAYMENT_PAYEE_MIDDLE_NAME { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERINGS_ACCEPTED_OR_REJECTED { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERINGS_ACCEPTANCE_NOTE { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERINGS_REJECTION_REASONS { get; set; }
        public Nullable<System.DateTime> CANCELLATION_DATE { get; set; }
        public string CANCELLATION_DEADLINE_NAME { get; set; }
        public Nullable<decimal> CANCELLATION_FEE_AMOUNT { get; set; }
        public string CANCELLATION_FEE_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<bool> CANCELLATION_REFUND_BANK_TRANSFER_SELECTED { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_BANK_TRANSFER_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_BANK_TRANSFER_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<System.DateTime> CANCELLATION_REFUND_BANK_TRANSFER_DATE { get; set; }
        public string CANCELLATION_REFUND_BANK_TRANSFER_PROCESSED_UserName { get; set; }
        public Nullable<bool> CANCELLATION_REFUND_CREDIT_CARD_PAYMENT_SELECTED { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_CREDIT_CARD_PAYMENT_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_CREDIT_CARD_PAYMENT_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<System.DateTime> CANCELLATION_REFUND_CREDIT_CARD_PAYMENT_DATE { get; set; }
        public string CANCELLATION_REFUND_CREDIT_CARD_PAYMENT_PROCESSED_UserName { get; set; }
        public Nullable<bool> CANCELLATION_REFUND_PAYPAL_PAYMENT_SELECTED { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_PAYPAL_PAYMENT_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_PAYPAL_PAYMENT_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<System.DateTime> CANCELLATION_REFUND_PAYPAL_PAYMENT_DATE { get; set; }
        public string CANCELLATION_REFUND_PAYPAL_PAYMENT_PROCESSED_UserName { get; set; }
        public Nullable<bool> CANCELLATION_REFUND_CHECK_PAYMENT_SELECTED { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_CHECK_PAYMENT_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_CHECK_PAYMENT_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<System.DateTime> CANCELLATION_REFUND_CHECK_PAYMENT_DATE { get; set; }
        public string CANCELLATION_REFUND_CHECK_PAYMENT_PROCESSED_UserName { get; set; }
        public Nullable<bool> CANCELLATION_REFUND_ONSITE_CASH_PAYMENT_SELECTED { get; set; }
        public Nullable<decimal> CANCELLATION_REFUND_ONSITE_CASH_PAYMENT_AMOUNT { get; set; }
        public string CANCELLATION_REFUND_ONSITE_CASH_PAYMENT_AMOUNT_CURRENCY_UOM_NAME { get; set; }
        public Nullable<System.DateTime> CANCELLATION_REFUND_ONSITE_CASH_PAYMENT_DATE { get; set; }
        public string CANCELLATION_REFUND_ONSITE_CASH_PAYMENT_PROCESSED_UserName { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CONFERENCE_REGISTRATION_PACKAGE CONFERENCE_REGISTRATION_PACKAGE { get; set; }
    }
}
