//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT_FOR_CONFERENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT_FOR_CONFERENCE()
        {
            this.MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE = new HashSet<MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE>();
        }
    
        public string UserName { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_EMAIL { get; set; }
        public string Email { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_NAME_EN { get; set; }
        public string IsRegOrGenforConf { get; set; }
        public Nullable<System.DateTime> Reg_GenforConfDate { get; set; }
        public string Reg_GenforConf_UserName { get; set; }
        public Nullable<decimal> Reg_GenforConf_PERSON_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuspended { get; set; }
        public Nullable<bool> CONFERENCE_ADMIN_RIGHT { get; set; }
        public string CONFERENCE_ADMIN_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> CONFERENCE_ADMIN_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> CONFERENCE_ADMIN_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> REVIEWER_RIGHT { get; set; }
        public string REVIEWER_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> REVIEWER_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> REVIEWER_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> AUTHOR_RIGHT { get; set; }
        public string AUTHOR_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> AUTHOR_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> AUTHOR_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> PRESENTER_RIGHT { get; set; }
        public string PRESENTER_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> PRESENTER_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> PRESENTER_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> CONFERENCE_ATTENDEE_RIGHT { get; set; }
        public string CONFERENCE_ATTENDEE_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> CONFERENCE_ATTENDEE_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> CONFERENCE_ATTENDEE_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> SUPPORT_STAFF_RIGHT { get; set; }
        public string SUPPORT_STAFF_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> SUPPORT_STAFF_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> SUPPORT_STAFF_RIGHT_SETTING_DATE { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CONFERENCE CONFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE> MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE { get; set; }
    }
}
