//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_TYPE_NAME
    {
        public string TYPE_NAME_ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string TYPE_NAME_NAME { get; set; }
        public string TYPE_NAME_NAME_EN { get; set; }
        public string TYPE_NAME_NAME_SHORT { get; set; }
        public string TYPE_NAME_NAME_SHORT_EN { get; set; }
        public string TYPE_VALUE { get; set; }
    }
}
