//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPROVED_CONFERENCE_ATTENDEE_TYPES
    {
        public decimal CONFERENCE_REGISTRATION_PACKAGE_CONDITION_ID { get; set; }
        public decimal CONFERENCE_ATTENDEE_TYPE_ID { get; set; }
        public string CONFERENCE_ATTENDEE_TYPE_NAME { get; set; }
        public string CONFERENCE_ATTENDEE_TYPE_NAME_EN { get; set; }
    
        public virtual CONFERENCE_ATTENDEE_TYPE CONFERENCE_ATTENDEE_TYPE { get; set; }
        public virtual CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS { get; set; }
    }
}
