//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTHOR()
        {
            this.AUTHOR_PAPER_ABSTRACT_RELATIONSHIP = new HashSet<AUTHOR_PAPER_ABSTRACT_RELATIONSHIP>();
            this.AUTHOR_PAPER_TEXT_RELATIONSHIP = new HashSet<AUTHOR_PAPER_TEXT_RELATIONSHIP>();
        }
    
        public decimal PERSON_ID { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_PERSONAL_TITLE { get; set; }
        public string CURRENT_SUFFIX { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_NAME_EN { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHOR_PAPER_ABSTRACT_RELATIONSHIP> AUTHOR_PAPER_ABSTRACT_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHOR_PAPER_TEXT_RELATIONSHIP> AUTHOR_PAPER_TEXT_RELATIONSHIP { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
