//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_SETTING_RIGHTS
    {
        public decimal CONFERENCE_ID { get; set; }
        public Nullable<decimal> SUGGESTED_PAPER_ABSTRACT_AUTOMATIC_APPROVAL_PERCENTILE { get; set; }
        public Nullable<decimal> SUGGESTED_PAPER_ABSTRACT_AUTOMATIC_REJECTION_PERCENTILE { get; set; }
        public Nullable<decimal> SUGGESTED_PAPER_TEXT_AUTOMATIC_APPROVAL_PERCENTILE { get; set; }
        public Nullable<decimal> SUGGESTED_PAPER_TEXT_AUTOMATIC_REJECTION_PERCENTILE { get; set; }
        public Nullable<decimal> TECHNICAL_CHAIR_RIGHT_PERSON_ID_1 { get; set; }
        public string TECHNICAL_CHAIR_RIGHT_SCRIPT_1 { get; set; }
        public Nullable<decimal> TECHNICAL_CHAIR_RIGHT_PERSON_ID_2 { get; set; }
        public string TECHNICAL_CHAIR_RIGHT_SCRIPT_2 { get; set; }
        public Nullable<decimal> TECHNICAL_CHAIR_RIGHT_PERSON_ID_3 { get; set; }
        public string TECHNICAL_CHAIR_RIGHT_SCRIPT_3 { get; set; }
        public Nullable<decimal> TECHNICAL_CHAIR_RIGHT_PERSON_ID_4 { get; set; }
        public string TECHNICAL_CHAIR_RIGHT_SCRIPT_4 { get; set; }
        public Nullable<decimal> TECHNICAL_CHAIR_RIGHT_PERSON_ID_5 { get; set; }
        public string TECHNICAL_CHAIR_RIGHT_SCRIPT_5 { get; set; }
        public Nullable<decimal> SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_1 { get; set; }
        public string SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_1 { get; set; }
        public Nullable<decimal> SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_2 { get; set; }
        public string SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_2 { get; set; }
        public Nullable<decimal> SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_3 { get; set; }
        public string SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_3 { get; set; }
        public Nullable<decimal> SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_4 { get; set; }
        public string SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_4 { get; set; }
        public Nullable<decimal> SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_5 { get; set; }
        public string SETTING_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_5 { get; set; }
        public Nullable<decimal> SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_1 { get; set; }
        public string SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_1 { get; set; }
        public Nullable<decimal> SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_2 { get; set; }
        public string SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_2 { get; set; }
        public Nullable<decimal> SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_3 { get; set; }
        public string SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_3 { get; set; }
        public Nullable<decimal> SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_4 { get; set; }
        public string SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_4 { get; set; }
        public Nullable<decimal> SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_5 { get; set; }
        public string SETTING_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_5 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_1 { get; set; }
        public string SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_1 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_2 { get; set; }
        public string SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_2 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_3 { get; set; }
        public string SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_3 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_4 { get; set; }
        public string SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_4 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_5 { get; set; }
        public string SETTING_FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_5 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_1 { get; set; }
        public string SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_1 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_2 { get; set; }
        public string SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_2 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_3 { get; set; }
        public string SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_3 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_4 { get; set; }
        public string SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_4 { get; set; }
        public Nullable<decimal> SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_PERSON_ID_5 { get; set; }
        public string SETTING_FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT_5 { get; set; }
    }
}
