//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE
    {
        public decimal CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_ID { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_NAME { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_NAME_EN { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_DESCRIPTION { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_DESCRIPTION_EN { get; set; }
    }
}
