//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_ATTENDEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFERENCE_ATTENDEE()
        {
            this.CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION = new HashSet<CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION>();
        }
    
        public decimal PERSON_ID { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_PERSONAL_TITLE { get; set; }
        public string CURRENT_SUFFIX { get; set; }
        public Nullable<decimal> CURRENT_HOME_ORGANIZATION_ID { get; set; }
        public string CURRENT_HOME_ORGANIZATION_NAME { get; set; }
        public string CURRENT_HOME_ORGANIZATION_NAME_EN { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_NAME_EN { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_1 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_2 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_3 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_4 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_5 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_6 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_7 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_8 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_9 { get; set; }
        public Nullable<decimal> REGISTERED_CONFERENCE_REGISTRATION_PACKAGE_ID_10 { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION> CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
