//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT
    {
        public decimal PAPER_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public short PRESENTATION_SLOT_NUMBER { get; set; }
        public string ON_SCHEDULE_OR_CANCELLED_OR_MOVED_PRESENTATION_SLOT { get; set; }
        public Nullable<System.DateTime> PRESENTATION_SLOT_ACTUAL_START_DATETIME { get; set; }
        public Nullable<System.DateTime> PRESENTATION_SLOT_ACTUAL_END_DATETIME { get; set; }
        public string ON_TIME_START_OR_EARLY_START_OR_LATE_START { get; set; }
        public string ON_TIME_END_OR_EARLY_END_OR_LATE_END { get; set; }
        public Nullable<decimal> MOVED_TO_CONFERENCE_SESSION_ID { get; set; }
        public Nullable<short> MOVED_TO_PRESENTATION_SLOT_NUMBER { get; set; }
        public string NOTE { get; set; }
    
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
        public virtual PAPER_TEXT PAPER_TEXT { get; set; }
    }
}
