//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_REGISTRATION_PACKAGE_OFFERING
    {
        public decimal CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID { get; set; }
        public Nullable<decimal> CONFERENCE_ID { get; set; }
        public Nullable<decimal> CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_ID { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_NAME { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE_NAME_EN { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN { get; set; }
        public Nullable<decimal> CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE { get; set; }
        public string CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
    }
}
