//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP
    {
        public decimal PERSON_ID { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
    
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
        public virtual CONFERENCE_SESSION_CHAIR CONFERENCE_SESSION_CHAIR { get; set; }
    }
}
