//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS()
        {
            this.APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE = new HashSet<APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE>();
            this.APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS = new HashSet<APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS>();
            this.APPROVED_CONFERENCE_ATTENDEE_TYPES = new HashSet<APPROVED_CONFERENCE_ATTENDEE_TYPES>();
        }
    
        public decimal CONFERENCE_REGISTRATION_PACKAGE_CONDITION_ID { get; set; }
        public Nullable<short> CONFERENCE_ATTENDEE_AGE_FROM { get; set; }
        public Nullable<short> CONFERENCE_ATTENDEE_AGE_TO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE> APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS> APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVED_CONFERENCE_ATTENDEE_TYPES> APPROVED_CONFERENCE_ATTENDEE_TYPES { get; set; }
        public virtual CONFERENCE_REGISTRATION_PACKAGE CONFERENCE_REGISTRATION_PACKAGE { get; set; }
    }
}
