//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_SESSION_CHAIR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFERENCE_SESSION_CHAIR()
        {
            this.CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP = new HashSet<CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP>();
        }
    
        public decimal PERSON_ID { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_PERSONAL_TITLE { get; set; }
        public string CURRENT_SUFFIX { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_NAME_EN { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP> CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
