//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFERENCE_ATTENDEE_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONFERENCE_ATTENDEE_TYPE()
        {
            this.APPROVED_CONFERENCE_ATTENDEE_TYPES = new HashSet<APPROVED_CONFERENCE_ATTENDEE_TYPES>();
        }
    
        public decimal CONFERENCE_ATTENDEE_TYPE_ID { get; set; }
        public string CONFERENCE_ATTENDEE_TYPE_NAME { get; set; }
        public string CONFERENCE_ATTENDEE_TYPE_NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVED_CONFERENCE_ATTENDEE_TYPES> APPROVED_CONFERENCE_ATTENDEE_TYPES { get; set; }
    }
}
