//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT> ACCOUNTs { get; set; }
        public virtual DbSet<ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP> ACCOUNT_CONFERENCE_REGISTRATION_PACKAGE_RELATIONSHIP { get; set; }
        public virtual DbSet<ACCOUNT_FOR_CONFERENCE> ACCOUNT_FOR_CONFERENCE { get; set; }
        public virtual DbSet<ALL_TYPE_NAME> ALL_TYPE_NAME { get; set; }
        public virtual DbSet<APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE> APPROVED_CONFERENCE_ATTENDEE_GENDER_TYPE { get; set; }
        public virtual DbSet<APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS> APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS { get; set; }
        public virtual DbSet<APPROVED_CONFERENCE_ATTENDEE_TYPES> APPROVED_CONFERENCE_ATTENDEE_TYPES { get; set; }
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<AUTHOR_PAPER_ABSTRACT_RELATIONSHIP> AUTHOR_PAPER_ABSTRACT_RELATIONSHIP { get; set; }
        public virtual DbSet<AUTHOR_PAPER_TEXT_RELATIONSHIP> AUTHOR_PAPER_TEXT_RELATIONSHIP { get; set; }
        public virtual DbSet<CONFERENCE> CONFERENCEs { get; set; }
        public virtual DbSet<CONFERENCE_ATTENDEE> CONFERENCE_ATTENDEE { get; set; }
        public virtual DbSet<CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION> CONFERENCE_ATTENDEE_IN_REGISTERED_CONFERENCE_SESSION { get; set; }
        public virtual DbSet<CONFERENCE_ATTENDEE_TYPE> CONFERENCE_ATTENDEE_TYPE { get; set; }
        public virtual DbSet<CONFERENCE_BOARD_OF_REVIEW> CONFERENCE_BOARD_OF_REVIEW { get; set; }
        public virtual DbSet<CONFERENCE_FIELD_OF_STUDY_RELATIONSHIP> CONFERENCE_FIELD_OF_STUDY_RELATIONSHIP { get; set; }
        public virtual DbSet<CONFERENCE_PRESENTATION_TYPE> CONFERENCE_PRESENTATION_TYPE { get; set; }
        public virtual DbSet<CONFERENCE_REGISTRATION_PACKAGE> CONFERENCE_REGISTRATION_PACKAGE { get; set; }
        public virtual DbSet<CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS> CONFERENCE_REGISTRATION_PACKAGE_CONDITIONS { get; set; }
        public virtual DbSet<CONFERENCE_REGISTRATION_PACKAGE_OFFERING> CONFERENCE_REGISTRATION_PACKAGE_OFFERING { get; set; }
        public virtual DbSet<CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE> CONFERENCE_REGISTRATION_PACKAGE_OFFERING_TYPE { get; set; }
        public virtual DbSet<CONFERENCE_SESSION> CONFERENCE_SESSION { get; set; }
        public virtual DbSet<CONFERENCE_SESSION_CHAIR> CONFERENCE_SESSION_CHAIR { get; set; }
        public virtual DbSet<CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP> CONFERENCE_SESSION_CHAIR_CONFERENCE_SESSION_RELATIONSHIP { get; set; }
        public virtual DbSet<CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT> CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT { get; set; }
        public virtual DbSet<CONFERENCE_SESSION_TOPIC> CONFERENCE_SESSION_TOPIC { get; set; }
        public virtual DbSet<CONFERENCE_SETTING_RIGHTS> CONFERENCE_SETTING_RIGHTS { get; set; }
        public virtual DbSet<CONFERENCE_TYPE> CONFERENCE_TYPE { get; set; }
        public virtual DbSet<CONFERENCE_TYPE_OF_STUDY_RELATIONSHIP> CONFERENCE_TYPE_OF_STUDY_RELATIONSHIP { get; set; }
        public virtual DbSet<COUNTRY> COUNTRies { get; set; }
        public virtual DbSet<FACILITY> FACILITies { get; set; }
        public virtual DbSet<FIELD_OF_STUDY> FIELD_OF_STUDY { get; set; }
        public virtual DbSet<GENDER_TYPE> GENDER_TYPE { get; set; }
        public virtual DbSet<LINE_OF_BUSINES_TYPE> LINE_OF_BUSINES_TYPE { get; set; }
        public virtual DbSet<MOBILEFORM_FUNCTION> MOBILEFORM_FUNCTION { get; set; }
        public virtual DbSet<MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU> MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU { get; set; }
        public virtual DbSet<MOBILEFORM_GROUP> MOBILEFORM_GROUP { get; set; }
        public virtual DbSet<MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE> MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE { get; set; }
        public virtual DbSet<MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE> MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE { get; set; }
        public virtual DbSet<MOBILEFORM_GROUP_MENU_FOR_CONFERENCE> MOBILEFORM_GROUP_MENU_FOR_CONFERENCE { get; set; }
        public virtual DbSet<MOBILEFORM_MENU> MOBILEFORM_MENU { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATIONs { get; set; }
        public virtual DbSet<PAPER_ABSTRACT> PAPER_ABSTRACT { get; set; }
        public virtual DbSet<PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW> PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW { get; set; }
        public virtual DbSet<PAPER_TEXT> PAPER_TEXT { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<PRESENTER> PRESENTERs { get; set; }
        public virtual DbSet<PRESENTER_CONFERENCE_SESSION_RELATIONSHIP> PRESENTER_CONFERENCE_SESSION_RELATIONSHIP { get; set; }
        public virtual DbSet<REGISTERED_CONFERENCE_SESSION_IN_CONFERENCE_REGISTRATION_PACKAGE> REGISTERED_CONFERENCE_SESSION_IN_CONFERENCE_REGISTRATION_PACKAGE { get; set; }
        public virtual DbSet<REVIEWER> REVIEWERs { get; set; }
        public virtual DbSet<REVIEWER_PAPER_ABSTRACT_RELATIONSHIP> REVIEWER_PAPER_ABSTRACT_RELATIONSHIP { get; set; }
        public virtual DbSet<REVIEWER_PAPER_TEXT_RELATIONSHIP> REVIEWER_PAPER_TEXT_RELATIONSHIP { get; set; }
        public virtual DbSet<SESSION_TOPIC_CONFERENCE_PRESENTATION_TYPE> SESSION_TOPIC_CONFERENCE_PRESENTATION_TYPE { get; set; }
        public virtual DbSet<SUPPORT_STAFF> SUPPORT_STAFF { get; set; }
        public virtual DbSet<SUPPORT_STAFF_CONFERENCE_SESSION_RELATIONSHIP> SUPPORT_STAFF_CONFERENCE_SESSION_RELATIONSHIP { get; set; }
        public virtual DbSet<TYPE_OF_STUDY> TYPE_OF_STUDY { get; set; }
    }
}
