//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        public decimal FACILITY_ID { get; set; }
        public string FACILITY_NAME { get; set; }
        public string FACILITY_NAME_EN { get; set; }
        public string FACILITY_TYPE_NAME { get; set; }
        public string FACILITY_TYPE_NAME_EN { get; set; }
        public string AREA { get; set; }
        public Nullable<int> MAX_NUMBER_OF_PEOPLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> ROOT_FACILITY_ID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string DISTRICT { get; set; }
        public string STATE { get; set; }
        public string WARD { get; set; }
        public string FACILITY_USAGE_STATUS { get; set; }
    }
}
