//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE_OF_BUSINES_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINE_OF_BUSINES_TYPE()
        {
            this.APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS = new HashSet<APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS>();
        }
    
        public decimal LINE_OF_BUSINESS_TYPE_ID { get; set; }
        public string LINE_OF_BUSINESS_TYPE_NAME { get; set; }
        public string LINE_OF_BUSINESS_TYPE_NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS> APPROVED_CONFERENCE_ATTENDEE_LINE_OF_BUSINESS { get; set; }
    }
}
