//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILEFORM_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBILEFORM_GROUP()
        {
            this.MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE = new HashSet<MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE>();
            this.MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE = new HashSet<MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE>();
        }
    
        public decimal GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_NAME_EN { get; set; }
        public string DESIGNATED_CONFERENCE_USER_TYPE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public Nullable<decimal> ROOT_GROUP_ID { get; set; }
        public Nullable<decimal> GROUP_ORDER_NUMBER { get; set; }
        public string CREATED_UserName { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_UserName { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE> MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE> MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE { get; set; }
    }
}
