//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU
    {
        public decimal FUNCTION_ID { get; set; }
        public decimal MENU_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public string MOBILEAPP_OR_MOBILEWEB { get; set; }
        public string MOBILE_PLATFORM_NAME { get; set; }
        public string NOTE { get; set; }
        public string NOTE_EN { get; set; }
        public string CREATED_UserName { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_UserName { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    
        public virtual MOBILEFORM_FUNCTION MOBILEFORM_FUNCTION { get; set; }
        public virtual MOBILEFORM_MENU MOBILEFORM_MENU { get; set; }
    }
}
