//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILEFORM_GROUP_ACCOUNT_FOR_CONFERENCE
    {
        public decimal GROUP_ID { get; set; }
        public string UserName { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public string NOTE { get; set; }
        public string NOTE_EN { get; set; }
    
        public virtual ACCOUNT_FOR_CONFERENCE ACCOUNT_FOR_CONFERENCE { get; set; }
        public virtual MOBILEFORM_GROUP MOBILEFORM_GROUP { get; set; }
    }
}
