//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOBILEFORM_FUNCTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOBILEFORM_FUNCTION()
        {
            this.MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU = new HashSet<MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU>();
            this.MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE = new HashSet<MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE>();
        }
    
        public decimal FUNCTION_ID { get; set; }
        public string FUNCTION_NAME { get; set; }
        public string FUNCTION_NAME_EN { get; set; }
        public string MOBILEAPP_OR_MOBILEWEB { get; set; }
        public string MOBILE_PLATFORM_NAME { get; set; }
        public string FORM_NAME { get; set; }
        public string FORM_NAME_EN { get; set; }
        public string FORM_URL { get; set; }
        public Nullable<bool> FORM_DEACTIVATED { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public string FORM_ICON { get; set; }
        public string SYSTEM_OR_USER_FUNCTION { get; set; }
        public string CREATED_UserName { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_UserName { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU> MOBILEFORM_FUNCTION_FOR_MOBILEFORM_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE> MOBILEFORM_GROUP_FUNCTION_FOR_CONFERENCE { get; set; }
    }
}
