//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATION
    {
        public decimal ORGANIZATION_ID { get; set; }
        public string ORGANIZATION_CODE { get; set; }
        public string ORGANIZATION_NAME { get; set; }
        public string ORGANIZATION_NAME_EN { get; set; }
        public string ADDRESS { get; set; }
        public string WARD { get; set; }
        public string DISTRICT { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ORGANIZATION_TELEPHONE { get; set; }
        public string ORGANIZATION_FAX { get; set; }
        public string ORGANIZATION_EMAIL { get; set; }
        public string ORGANIZATION_WEBSITE { get; set; }
        public string ZIPCODE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public Nullable<System.DateTime> ESTABLISHED_DATE { get; set; }
        public Nullable<decimal> ESTABLISHMENT_DOCUMENT_ID { get; set; }
        public string ORGANIZATION_LOGO { get; set; }
        public byte[] ORGANIZATION_LOGO_FILE { get; set; }
        public Nullable<decimal> ROOT_ORGANIZATION_ID { get; set; }
        public Nullable<decimal> ORGANIZATION_ORDER_NUMBER { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public string DELETED_SCRIPT { get; set; }
    }
}
