//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW()
        {
            this.REVIEWER_PAPER_TEXT_RELATIONSHIP = new HashSet<REVIEWER_PAPER_TEXT_RELATIONSHIP>();
        }
    
        public decimal CONFERENCE_BOARD_OF_REVIEW_ID { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public decimal PAPER_ID { get; set; }
        public short PAPER_TEXT_SUBMISSION_DEADLINE_ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE { get; set; }
        public Nullable<System.DateTime> FIRST_REVIEWED_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_REVIEWED_DATE { get; set; }
        public Nullable<bool> WITHDRAWN { get; set; }
        public Nullable<System.DateTime> WITHDRAWN_DATE { get; set; }
        public Nullable<bool> FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT { get; set; }
        public string FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_SCRIPT { get; set; }
        public Nullable<System.DateTime> FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_DATE { get; set; }
        public Nullable<decimal> FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_REVIEWER_PERSON_ID { get; set; }
        public Nullable<decimal> FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_ID { get; set; }
        public string FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME { get; set; }
        public string FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN { get; set; }
        public string FINAL_APPROVED_FULL_PAPER_OR_WORK_IN_PROGRESS { get; set; }
        public Nullable<decimal> FINAL_APPROVED_TYPE_OF_STUDY_ID { get; set; }
        public string FINAL_APPROVED_TYPE_OF_STUDY_NAME { get; set; }
        public string FINAL_APPROVED_TYPE_OF_STUDY_NAME_EN { get; set; }
        public Nullable<bool> FINAL_APPROVED_FOR_PRESENTATION { get; set; }
        public Nullable<decimal> FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_ID { get; set; }
        public string FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_NAME { get; set; }
        public string FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWER_PAPER_TEXT_RELATIONSHIP> REVIEWER_PAPER_TEXT_RELATIONSHIP { get; set; }
    }
}
