//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAPER_TEXT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAPER_TEXT()
        {
            this.AUTHOR_PAPER_TEXT_RELATIONSHIP = new HashSet<AUTHOR_PAPER_TEXT_RELATIONSHIP>();
            this.CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT = new HashSet<CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT>();
            this.PRESENTER_CONFERENCE_SESSION_RELATIONSHIP = new HashSet<PRESENTER_CONFERENCE_SESSION_RELATIONSHIP>();
            this.REVIEWER_PAPER_TEXT_RELATIONSHIP = new HashSet<REVIEWER_PAPER_TEXT_RELATIONSHIP>();
        }
    
        public decimal PAPER_ID { get; set; }
        public string PAPER_NUMBER_OR_CODE { get; set; }
        public string PAPER_TEXT_TITLE_1 { get; set; }
        public string PAPER_TEXT_TITLE_EN_1 { get; set; }
        public string PAPER_TEXT_1 { get; set; }
        public string PAPER_TEXT_EN_1 { get; set; }
        public string PAPER_TEXT_ATTACHED_FILENAME_1 { get; set; }
        public Nullable<short> NUMBER_OF_PAGES_OF_PAPER_TEXT_1 { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE_1 { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE_1 { get; set; }
        public string PAPER_TEXT_TITLE_2 { get; set; }
        public string PAPER_TEXT_TITLE_EN_2 { get; set; }
        public string PAPER_TEXT_2 { get; set; }
        public string PAPER_TEXT_EN_2 { get; set; }
        public string PAPER_TEXT_ATTACHED_FILENAME_2 { get; set; }
        public Nullable<short> NUMBER_OF_PAGES_OF_PAPER_TEXT_2 { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE_2 { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE_2 { get; set; }
        public string PAPER_TEXT_TITLE_3 { get; set; }
        public string PAPER_TEXT_TITLE_EN_3 { get; set; }
        public string PAPER_TEXT_3 { get; set; }
        public string PAPER_TEXT_EN_3 { get; set; }
        public string PAPER_TEXT_ATTACHED_FILENAME_3 { get; set; }
        public Nullable<short> NUMBER_OF_PAGES_OF_PAPER_TEXT_3 { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE_3 { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE_3 { get; set; }
        public string PAPER_TEXT_TITLE_4 { get; set; }
        public string PAPER_TEXT_TITLE_EN_4 { get; set; }
        public string PAPER_TEXT_4 { get; set; }
        public string PAPER_TEXT_EN_4 { get; set; }
        public string PAPER_TEXT_ATTACHED_FILENAME_4 { get; set; }
        public Nullable<short> NUMBER_OF_PAGES_OF_PAPER_TEXT_4 { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE_4 { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE_4 { get; set; }
        public string PAPER_TEXT_TITLE_5 { get; set; }
        public string PAPER_TEXT_TITLE_EN_5 { get; set; }
        public string PAPER_TEXT_5 { get; set; }
        public string PAPER_TEXT_EN_5 { get; set; }
        public string PAPER_TEXT_ATTACHED_FILENAME_5 { get; set; }
        public Nullable<short> NUMBER_OF_PAGES_OF_PAPER_TEXT_5 { get; set; }
        public Nullable<System.DateTime> FIRST_SUBMITTED_DATE_5 { get; set; }
        public Nullable<System.DateTime> LAST_REVISED_DATE_5 { get; set; }
        public Nullable<bool> PAPER_TEXT_WITHDRAWN { get; set; }
        public string PAPER_TEXT_WITHDRAWN_SCRIPT { get; set; }
        public Nullable<System.DateTime> PAPER_TEXT_WITHDRAWN_DATE { get; set; }
        public string PAPER_TEXT_WITHDRAWN_NOTE { get; set; }
        public Nullable<bool> FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT { get; set; }
        public string FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_SCRIPT { get; set; }
        public Nullable<System.DateTime> FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_DATE { get; set; }
        public decimal FINAL_APPROVAL_OR_REJECTION_OF_PAPER_TEXT_REVIEWER_PERSON_ID { get; set; }
        public Nullable<decimal> FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_ID { get; set; }
        public string FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME { get; set; }
        public string FINAL_ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN { get; set; }
        public string FINAL_APPROVED_FULL_PAPER_OR_WORK_IN_PROGRESS { get; set; }
        public Nullable<decimal> FINAL_APPROVED_TYPE_OF_STUDY_ID { get; set; }
        public string FINAL_APPROVED_TYPE_OF_STUDY_NAME { get; set; }
        public string FINAL_APPROVED_TYPE_OF_STUDY_NAME_EN { get; set; }
        public Nullable<bool> FINAL_APPROVED_FOR_PRESENTATION { get; set; }
        public Nullable<decimal> FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_ID { get; set; }
        public string FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_NAME { get; set; }
        public string FINAL_APPROVED_CONFERENCE_PRESENTATION_TYPE_NAME_EN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHOR_PAPER_TEXT_RELATIONSHIP> AUTHOR_PAPER_TEXT_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT> CONFERENCE_SESSION_PAPER_PRESENTATION_SLOT { get; set; }
        public virtual PAPER_ABSTRACT PAPER_ABSTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESENTER_CONFERENCE_SESSION_RELATIONSHIP> PRESENTER_CONFERENCE_SESSION_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWER_PAPER_TEXT_RELATIONSHIP> REVIEWER_PAPER_TEXT_RELATIONSHIP { get; set; }
    }
}
