//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON()
        {
            this.AUTHORs = new HashSet<AUTHOR>();
            this.CONFERENCE_ATTENDEE = new HashSet<CONFERENCE_ATTENDEE>();
            this.CONFERENCE_SESSION_CHAIR = new HashSet<CONFERENCE_SESSION_CHAIR>();
            this.PRESENTERs = new HashSet<PRESENTER>();
            this.REVIEWERs = new HashSet<REVIEWER>();
            this.SUPPORT_STAFF = new HashSet<SUPPORT_STAFF>();
        }
    
        public decimal PERSON_ID { get; set; }
        public string INSTRUCTOR_ID_NUMBER { get; set; }
        public string STUDENT_ID_NUMBER { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_PERSONAL_TITLE { get; set; }
        public string CURRENT_SUFFIX { get; set; }
        public string CURRENT_NICKNAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string MOTHER_S_MAIDEN_NAME { get; set; }
        public string CURRENT_MARITAL_STATUS { get; set; }
        public string PEOPLE_ID_NUMBER { get; set; }
        public Nullable<System.DateTime> PEOPLE_ID_ISSUE_DATE { get; set; }
        public string PEOPLE_ID_ISSUE_PLACE { get; set; }
        public string SOCIAL_SECURITY_NUMBER { get; set; }
        public string CURRENT_MAJOR_CITIZENSHIP { get; set; }
        public string CURRENT_PASSPORT_NUMBER { get; set; }
        public string CURRENT_PASSPORT_ISSUE_PLACE { get; set; }
        public Nullable<System.DateTime> CURRENT_PASSPORT_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> CURRENT_PASSPORT_EXPIRATION_DATE { get; set; }
        public Nullable<decimal> TOTAL_YEARS_WORK_EXPERIENCE { get; set; }
        public string COMMENTS { get; set; }
        public string ACADEMIC_TITLE { get; set; }
        public string CLOSEUP_PICTURE_1 { get; set; }
        public string CLOSEUP_PICTURE_2 { get; set; }
        public string CURRENT_ADDRESS { get; set; }
        public string CURRENT_CITY { get; set; }
        public string CURRENT_COUNTRY { get; set; }
        public string CURRENT_DISTRICT { get; set; }
        public Nullable<decimal> CURRENT_GENDER { get; set; }
        public string CURRENT_STATE { get; set; }
        public string CURRENT_WARD { get; set; }
        public string HOME_ADDRESS { get; set; }
        public string HOME_CITY { get; set; }
        public string HOME_COUNTRY { get; set; }
        public string HOME_DISTRICT { get; set; }
        public string HOME_STATE { get; set; }
        public string HOME_WARD { get; set; }
        public string CURRENT_PHONE_NUMBER { get; set; }
        public string CURRENT_MOBILE_NUMBER { get; set; }
        public string CURRENT_PERSONAL_EMAIL { get; set; }
        public string CREATED_UserName { get; set; }
        public Nullable<System.DateTime> CREATED_DATETIME { get; set; }
        public string UPDATED_UserName { get; set; }
        public Nullable<System.DateTime> UPDATED_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHOR> AUTHORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_ATTENDEE> CONFERENCE_ATTENDEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONFERENCE_SESSION_CHAIR> CONFERENCE_SESSION_CHAIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESENTER> PRESENTERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWER> REVIEWERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPORT_STAFF> SUPPORT_STAFF { get; set; }
    }
}
