//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESENTER_CONFERENCE_SESSION_RELATIONSHIP
    {
        public decimal PERSON_ID { get; set; }
        public decimal PAPER_ID { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public short PRESENTATION_SLOT_NUMBER { get; set; }
        public Nullable<short> ACTUAL_PRESENTATION_SLOT_NUMBER { get; set; }
        public Nullable<System.DateTime> ACTUAL_PRESENTATION_SLOT_START_DATETIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_PRESENTATION_SLOT_END_DATETIME { get; set; }
        public Nullable<bool> ABSENT { get; set; }
    
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
        public virtual PAPER_TEXT PAPER_TEXT { get; set; }
        public virtual PRESENTER PRESENTER { get; set; }
    }
}
