//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTERED_CONFERENCE_SESSION_IN_CONFERENCE_REGISTRATION_PACKAGE
    {
        public decimal CONFERENCE_REGISTRATION_PACKAGE_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public decimal CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID { get; set; }
        public string NOTE { get; set; }
        public string NOTE_EN { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_EN { get; set; }
    
        public virtual CONFERENCE_REGISTRATION_PACKAGE CONFERENCE_REGISTRATION_PACKAGE { get; set; }
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
    }
}
