//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REVIEWER()
        {
            this.REVIEWER_PAPER_ABSTRACT_RELATIONSHIP = new HashSet<REVIEWER_PAPER_ABSTRACT_RELATIONSHIP>();
            this.REVIEWER_PAPER_TEXT_RELATIONSHIP = new HashSet<REVIEWER_PAPER_TEXT_RELATIONSHIP>();
        }
    
        public decimal PERSON_ID { get; set; }
        public string CURRENT_LAST_NAME { get; set; }
        public string CURRENT_FIRST_NAME { get; set; }
        public string CURRENT_MIDDLE_NAME { get; set; }
        public string CURRENT_PERSONAL_TITLE { get; set; }
        public string CURRENT_SUFFIX { get; set; }
        public decimal CONFERENCE_BOARD_OF_REVIEW_ID { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_NAME { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_NAME_EN { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_TITLE { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_TITLE_EN { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public string CONFERENCE_NAME { get; set; }
        public string CONFERENCE_NAME_EN { get; set; }
        public Nullable<bool> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT { get; set; }
        public string CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> CONFERENCE_BOARD_OF_REVIEW_CHAIR_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT { get; set; }
        public string PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT { get; set; }
        public string PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT { get; set; }
        public string FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> FINAL_PAPER_ABSTRACT_APPROVAL_OR_REJECTION_RIGHT_SETTING_DATE { get; set; }
        public Nullable<bool> FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT { get; set; }
        public string FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SCRIPT { get; set; }
        public Nullable<decimal> FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> FINAL_PAPER_TEXT_APPROVAL_OR_REJECTION_RIGHT_SETTING_DATE { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        public virtual CONFERENCE_BOARD_OF_REVIEW CONFERENCE_BOARD_OF_REVIEW { get; set; }
        public virtual PERSON PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWER_PAPER_ABSTRACT_RELATIONSHIP> REVIEWER_PAPER_ABSTRACT_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWER_PAPER_TEXT_RELATIONSHIP> REVIEWER_PAPER_TEXT_RELATIONSHIP { get; set; }
    }
}
