//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWER_PAPER_TEXT_RELATIONSHIP
    {
        public decimal PERSON_ID { get; set; }
        public decimal CONFERENCE_BOARD_OF_REVIEW_ID { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public decimal PAPER_ID { get; set; }
        public short PAPER_TEXT_SUBMISSION_DEADLINE_ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> REVIEWED_DATE { get; set; }
        public Nullable<decimal> PROPOSED_REVISED_CONFERENCE_SESSION_TOPIC_ID { get; set; }
        public string PROPOSED_REVISED_CONFERENCE_SESSION_TOPIC_NAME { get; set; }
        public string PROPOSED_REVISED_CONFERENCE_SESSION_TOPIC_NAME_EN { get; set; }
        public string PROPOSED_FULL_PAPER_OR_WORK_IN_PROGRESS { get; set; }
        public Nullable<decimal> PROPOSED_TYPE_OF_STUDY_ID { get; set; }
        public string PROPOSED_TYPE_OF_STUDY_NAME { get; set; }
        public string PROPOSED_TYPE_OF_STUDY_NAME_EN { get; set; }
        public Nullable<decimal> PROPOSED_CONFERENCE_PRESENTATION_TYPE_ID { get; set; }
        public string PROPOSED_CONFERENCE_PRESENTATION_TYPE_NAME { get; set; }
        public string PROPOSED_CONFERENCE_PRESENTATION_TYPE_NAME_EN { get; set; }
        public Nullable<decimal> PAPER_TEXT_REVIEW_RATING_POINT { get; set; }
        public string SIGNIFICANT_REVISION_OR_MINIMAL_REVISION_OR_REVISION_NEEDED_OR_NO_REVISION_NEEDED { get; set; }
        public string REVIEW_TEXT { get; set; }
        public string REVIEW_TEXT_EN { get; set; }
        public Nullable<bool> APPROVAL_OR_REJECTION_OF_PAPER_TEXT { get; set; }
        public string APPROVAL_OR_REJECTION_OF_PAPER_TEXT_SCRIPT { get; set; }
        public Nullable<System.DateTime> APPROVAL_OR_REJECTION_OF_PAPER_TEXT_DATE { get; set; }
    
        public virtual PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW PAPER_REVIEW_SUMUP_BY_CONFERENCE_BOARD_OF_REVIEW { get; set; }
        public virtual PAPER_TEXT PAPER_TEXT { get; set; }
        public virtual REVIEWER REVIEWER { get; set; }
    }
}
