//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_TOPIC_CONFERENCE_PRESENTATION_TYPE
    {
        public decimal CONFERENCE_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public decimal CONFERENCE_PRESENTATION_TYPE_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public Nullable<System.DateTime> SETTING_DATE { get; set; }
    
        public virtual CONFERENCE CONFERENCE { get; set; }
        public virtual CONFERENCE_PRESENTATION_TYPE CONFERENCE_PRESENTATION_TYPE { get; set; }
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
    }
}
