//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Entities_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORT_STAFF_CONFERENCE_SESSION_RELATIONSHIP
    {
        public decimal PERSON_ID { get; set; }
        public decimal CONFERENCE_ID { get; set; }
        public decimal CONFERENCE_SESSION_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public Nullable<System.DateTime> THRU_DATE { get; set; }
        public Nullable<bool> MC_ROLE { get; set; }
        public string MC_ROLE_SCRIPT { get; set; }
        public Nullable<decimal> MC_ROLE_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> MC_ROLE_SETTING_DATE { get; set; }
        public string MC_ROLE_NOTE { get; set; }
        public string MC_ROLE_NOTE_EN { get; set; }
        public Nullable<bool> TRANSLATOR_ROLE { get; set; }
        public string TRANSLATOR_ROLE_SCRIPT { get; set; }
        public Nullable<decimal> TRANSLATOR_ROLE_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> TRANSLATOR_ROLE_SETTING_DATE { get; set; }
        public string TRANSLATOR_ROLE_NOTE { get; set; }
        public string TRANSLATOR_ROLE_NOTE_EN { get; set; }
        public Nullable<bool> FandB_SUPPORT_ROLE { get; set; }
        public string FandB_SUPPORT_ROLE_SCRIPT { get; set; }
        public Nullable<decimal> FandB_SUPPORT_ROLE_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> FandB_SUPPORT_ROLE_SETTING_DATE { get; set; }
        public string FandB_SUPPORT_ROLE_NOTE { get; set; }
        public string FandB_SUPPORT_ROLE_NOTE_EN { get; set; }
        public Nullable<bool> TECHNICAL_SUPPORT_ROLE { get; set; }
        public string TECHNICAL_SUPPORT_ROLE_SCRIPT { get; set; }
        public Nullable<decimal> TECHNICAL_SUPPORT_ROLE_SETTING_PERSON_ID { get; set; }
        public Nullable<System.DateTime> TECHNICAL_SUPPORT_ROLE_SETTING_DATE { get; set; }
        public string TECHNICAL_SUPPORT_ROLE_NOTE { get; set; }
        public string TECHNICAL_SUPPORT_ROLE_NOTE_EN { get; set; }
    
        public virtual CONFERENCE_SESSION CONFERENCE_SESSION { get; set; }
        public virtual SUPPORT_STAFF SUPPORT_STAFF { get; set; }
    }
}
