//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoMS.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khoảng một phút trước.
        /// </summary>
        public static string About_a_minute_ago {
            get {
                return ResourceManager.GetString("About_a_minute_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khoảng một tháng trước.
        /// </summary>
        public static string About_a_month_ago {
            get {
                return ResourceManager.GetString("About_a_month_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khoảng một năm trước.
        /// </summary>
        public static string About_a_year_ago {
            get {
                return ResourceManager.GetString("About_a_year_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khoảng một giờ trước.
        /// </summary>
        public static string About_an_hour_ago {
            get {
                return ResourceManager.GetString("About_an_hour_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại..
        /// </summary>
        public static string Account_does_not_exist {
            get {
                return ResourceManager.GetString("Account_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhận được dữ liệu..
        /// </summary>
        public static string Data_not_received {
            get {
                return ResourceManager.GetString("Data_not_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày trước.
        /// </summary>
        public static string Days_ago {
            get {
                return ResourceManager.GetString("Days_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa danh sách tin nhắn thất bại..
        /// </summary>
        public static string Delete_list_message_fail {
            get {
                return ResourceManager.GetString("Delete_list_message_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại..
        /// </summary>
        public static string Email_already_exists {
            get {
                return ResourceManager.GetString("Email_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại..
        /// </summary>
        public static string Email_does_not_exist {
            get {
                return ResourceManager.GetString("Email_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ..
        /// </summary>
        public static string Email_invalid {
            get {
                return ResourceManager.GetString("Email_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khôi phục mật khẩu..
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giờ trước.
        /// </summary>
        public static string Hours_ago {
            get {
                return ResourceManager.GetString("Hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phút trước.
        /// </summary>
        public static string Minutes_ago {
            get {
                return ResourceManager.GetString("Minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tháng trước.
        /// </summary>
        public static string Months_ago {
            get {
                return ResourceManager.GetString("Months_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng..
        /// </summary>
        public static string Password_is_incorrect {
            get {
                return ResourceManager.GetString("Password_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được nhỏ hơn 6 ký tự..
        /// </summary>
        public static string Password_must_not_be_less_than_6_characters {
            get {
                return ResourceManager.GetString("Password_must_not_be_less_than_6_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email..
        /// </summary>
        public static string Please_enter_email {
            get {
                return ResourceManager.GetString("Please_enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ và tên..
        /// </summary>
        public static string Please_enter_fullname {
            get {
                return ResourceManager.GetString("Please_enter_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu..
        /// </summary>
        public static string Please_enter_password {
            get {
                return ResourceManager.GetString("Please_enter_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tài khoản..
        /// </summary>
        public static string Please_enter_username {
            get {
                return ResourceManager.GetString("Please_enter_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string Seconds_ago {
            get {
                return ResourceManager.GetString("Seconds_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyBuUdOTXwtg66HCjLJUw3rmyl-rdFw3LWo.
        /// </summary>
        public static string Server_fcm_key {
            get {
                return ResourceManager.GetString("Server_fcm_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi, đã có lỗi xảy ra..
        /// </summary>
        public static string Sorry_an_error_has_occurred {
            get {
                return ResourceManager.GetString("Sorry_an_error_has_occurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại..
        /// </summary>
        public static string Username_already_exists {
            get {
                return ResourceManager.GetString("Username_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được nhỏ hơn 6 ký tự..
        /// </summary>
        public static string Username_must_not_be_less_than_6_characters {
            get {
                return ResourceManager.GetString("Username_must_not_be_less_than_6_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tền tài khoản không tồn tại..
        /// </summary>
        public static string Username_name_does_not_exist {
            get {
                return ResourceManager.GetString("Username_name_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác..
        /// </summary>
        public static string Username_or_password_incorrect {
            get {
                return ResourceManager.GetString("Username_or_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to năm trước.
        /// </summary>
        public static string Years_ago {
            get {
                return ResourceManager.GetString("Years_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hôm qua.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have bookmark this person..
        /// </summary>
        public static string You_have_bookmark_this_person {
            get {
                return ResourceManager.GetString("You_have_bookmark_this_person", resourceCulture);
            }
        }
    }
}
